### ISSUE TITLE
Cannot be installed with Nix [includes PR]

### ISSUE THREAD

**Issue by higherorderfunctor** [alexwforsythe/tmux-which-key#2]
Awesome plugin!  Appreciate the work to make key binds more accessible.

I am unable to install with Nix as it makes the plugin directory read-only.  To remedy this I added some basic support for XDG directories to enable this plugin to be installed and used on immutable or declarative operating systems.

By default this would put he config in `~/.config/tmux/plugins/tmux-which-key` and the generated init file in `~/.local/share/tmux/plugins/tmux-which-key`.

I also added an example config for installing with Nix via Home Manager.  The config can be fully managed via Nix in a declarative manor.  The init file can then be written to a directory which is cleared every boot (immutable via temporary file system).

https://github.com/alexwforsythe/tmux-which-key/pull/1

**Comment by alexwforsythe** [comment]
Merged. Sorry for the delay, and thanks for your contribution!

**Comment by jasper-at-windswept** [comment]
@higherorderfunctor 
Now the PR has been merged how do I install this plugin for Tmux on NixOS with home manager?

I have this at the moment but when reloading my tmux i get the error `plugin/path` returned 1

```
  tmux-which-key = pkgs.tmuxPlugins.mkTmuxPlugin {
    pluginName = "plugin.sh";
    version = "1.0";
    src = pkgs.fetchFromGitHub {
      owner = "alexwforsythe";
      repo = "tmux-which-key";
      rev = "b4cd9d28da4d0a418d2af5f426a0d4b4e544ae10";
      hash = "sha256-ADUgh0sSs1N2AsLC7+LzZ8UPGnmMqvythy97lK4fYgw=";
    };
  };
```
The path is valid and is being found but something else is going wrong, what is the solution?

**Comment by higherorderfunctor** [comment]
@jasper-at-windswept I can take a look this weekend if my setup is still working.  Was working last time I used it, but its been a few weeks.

**Comment by higherorderfunctor** [comment]
@jasper-at-windswept there is a basic config in the README.  I only used the default config so did not go through the hassle of setting up python to convert the yaml to tmux.

https://github.com/alexwforsythe/tmux-which-key/blob/main/README.md?plain=1#L301-L336

I decided to work on a full module.  I can probably make a flake for this repo to make it easier to install, but it may take me a week or two as I have some other things I am working on.  I'll share what I am using now.

```nix
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.tmux.tmux-which-key;
  rtpPath = "tmux-plugins/tmux-which-key";
in {
  options.programs.tmux.tmux-which-key = {
    enable = lib.mkEnableOption "tmux-which-key";
    package = lib.mkPackageOption pkgs ["tmuxPlugins" "tmux-which-key"] {};
    settings = lib.mkOption {
      type = with lib.types; let
        valueType =
          nullOr (oneOf [
            bool
            int
            float
            str
            path
            (attrsOf valueType)
            (listOf valueType)
          ])
          // {
            description = "tmux-which-key configuration value";
          };
      in
        valueType;
      default = let
        fromYaml = file: let
          convertedJson =
            pkgs.runCommandNoCC "config.json" {
              nativeBuildInputs = [pkgs.yj];
            } ''
              ${lib.getExe pkgs.yj} < ${file} > $out
            '';
        in
          builtins.fromJSON (builtins.readFile "${convertedJson}");
      in
        fromYaml "${cfg.package}/share/tmux-plugins/tmux-which-key/config.example.yaml";
    };
  };

  config = let
    configYaml = lib.generators.toYAML {} cfg.settings;
    configTmux =
      pkgs.runCommandNoCC "init.tmux" {
        nativeBuildInputs = cfg.package.propagatedBuildInputs;
      } ''
        set -x
        echo '${configYaml}' > config.yaml
        python3 "${cfg.package}/share/tmux-plugins/tmux-which-key/plugin/build.py" \
          config.yaml $out
      '';
  in
    lib.mkIf cfg.enable {
      xdg = {
        configFile."${rtpPath}/config.yaml".text = configYaml;
        dataFile."${rtpPath}/init.tmux".source = configTmux;
      };
      programs.tmux.plugins = [
        {
          plugin = cfg.package;
          extraConfig = ''
            set -g @tmux-which-key-xdg-enable 1;
            set -g @tmux-which-key-disable-autobuild 1
            set -g @tmux-which-key-xdg-plugin-path "${rtpPath}"
          '';
        }
      ];
    };
}
```

**Comment by higherorderfunctor** [comment]
@jasper-at-windswept, I decided to just bang out the flake support and put in a PR: https://github.com/alexwforsythe/tmux-which-key/pull/9.

If you want to test it out early, you should just be able to replace all instances of `github:alexwforsythe/tmux-which-key` with `github:higherorderfunctor/tmux-which-key?ref=feat/adds-nix-flake` in the short term.  So something like below as your input and `nix run "github:higherorderfunctor/tmux-which-key?ref=feat/adds-nix-flake#generate-config"` to generate a config if going that configuration method.

```nix
    tmux-which-key = {
      url = "github:higherorderfunctor/tmux-which-key?ref=feat/adds-nix-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

I've updated my persona nixos-config to use this method for now.

**Comment by jasper-at-windswept** [comment]
Hey @higherorderfunctor 
Thanks so much for that. 
What is the generate config method just wondering?
I'm not quite sure how configuring this plugin works yet since I haven't been able to install it.

**Comment by higherorderfunctor** [comment]
@jasper-at-windswept it just converts the example config in the repo from YAML to Nix.  Essentially it goes YAML -> JSON -> Nix.

You can use straight YAML also.  I put an example in the README.

Can also just not supply a config at all to use the defaults.

**Comment by NovaViper** [comment]
Hey I'm getting together a PR to get this package added into Nixpkgs. Will link the PR once I get it together

**Comment by NovaViper** [comment]
Created the PR in case anyone's interested! https://github.com/NixOS/nixpkgs/pull/372455
